### ISSUE TITLE
how to use it？

### ISSUE THREAD

**Issue by fengmao31** [OpenRoberta/robertalab-naoclient#7]
![image](https://user-images.githubusercontent.com/19343842/112145479-61ec2580-8c15-11eb-8ce0-72c6e10d2905.png)

**Comment by hansmorb** [comment]
Click the start flag in the lower right, now you can touch the head and it will show you the token. It can not be used with the Virtual Robot, make sure you use the right version for the right robot.

**Comment by fengmao31** [comment]
you means OpenRoberta cannot control virtual NAO robot?

**Comment by hansmorb** [comment]
Yes, it can only be run on a real robot as far as I know

Samuel ***@***.***> schrieb am Di., 2. Nov. 2021, 20:41:

**Comment by fengmao31** [comment]
OK，thanks. it is 4.24 a.m. in china. I still wrong about my research proposal. 
do you know some information about german university which research on ROS robot and mutiple agents ? or university in other country.

**Comment by fengmao31** [comment]
I close it. thank you, hansmorb.
